name: Scheduled Test

on:
  schedule:
    # 设置一个在几分钟后会触发的时间 (UTC)
    # 例如，如果现在是 UTC 13:00，你可以设置为 '5 13 * * *'
    - cron: '02 13 * * *'
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Scheduled test workflow is running!"
